"""sensors and temperature data tables

Revision ID: 2a075375d251
Revises: 
Create Date: 2018-08-20 14:07:29.929545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a075375d251'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('serial_number', sa.String(length=15), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('serial_number')
    )
    op.create_index(op.f('ix_sensors_location'), 'sensors', ['location'], unique=True)
    op.create_table('temperature_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sensor_serial_number', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['sensor_serial_number'], ['sensors.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_data_timestamp'), 'temperature_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_data_timestamp'), table_name='temperature_data')
    op.drop_table('temperature_data')
    op.drop_index(op.f('ix_sensors_location'), table_name='sensors')
    op.drop_table('sensors')
    # ### end Alembic commands ###
