"""add maxmin table

Revision ID: fff2879d7e67
Revises: 2a075375d251
Create Date: 2018-08-27 23:01:30.564429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff2879d7e67'
down_revision = '2a075375d251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailymaxmindata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_of_reading', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('mintemp', sa.Float(), nullable=True),
    sa.Column('maxtemp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailymaxmindata')
    # ### end Alembic commands ###
